name: mediminutes
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.4.4 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_sign_in: ^6.2.2
  # flutter_bloc: ^8.1.6
  # equatable: ^2.0.5
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  gradient_borders: ^1.0.1
  country_pickers: ^3.0.1
  flutter_rating_bar: ^4.0.1
  responsive_grid_list: ^1.4.0
  carousel_slider_plus: ^7.0.0
  smooth_page_indicator: ^1.2.0+3
  

  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Be Vietnam Pro
      fonts: 
        - asset: assets/fonts/BeVietnamProBold.ttf
          weight: 700
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
    - family: Lateef
      fonts: 
        - asset: assets/fonts/Lateef.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        # - asset: assets/fonts/OpenSansRomanRegular.ttf
        #   weight: 400
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 800
       
